### ISSUE TITLE
Unable to install due to outdated manifest

### ISSUE THREAD

**Issue by dvaldivia** [vlad-tura/yaml-templates-intellij#4]
Hi, I'm trying to install this plugin but it seems that since it's manifest has not been updated in a while, it needs to be updated so it can be installed on newer IDEs

<img width="486" alt="Screenshot 2023-07-23 at 3 54 52 PM" src="https://github.com/vlad-tura/yaml-templates-intellij/assets/18384552/5baba984-c22b-4dca-8b8a-70650d4e1e53">

**Comment by vlad-tura** [comment]
Fixed in [0.0.4](https://github.com/vlad-tura/yaml-templates-intellij/releases/tag/v0.0.4), now compatible with all 2022 and 2023 IDEs

**Comment by vlad-tura** [comment]
Fixed in [0.0.4](https://github.com/vlad-tura/yaml-templates-intellij/releases/tag/v0.0.4), now compatible with all 2022 and 2023 IDEs
